version: '3.7'

services:
  mysql:
    container_name: app_mysql_test
    restart: always
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app_docker
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init-script.sql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.6-management-alpine
    hostname: my-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
  php:
    container_name: slim_php
    build:
      context: ./
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim_app
    links:
      - mysql
      - rabbitmq
    depends_on:
      - mysql
  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  mysql-data:
